### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by jaspreet-singh-sahota**
This assignment consists of making a clone of a New York Times article page
<aside> tag and floats are the main features to be used in this project

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
### Status: changes required🛑
# Hi Team🙂,
Your page is 👌, it looks almost like the original page. Semantic Html application in the project was nicely done too. Here are a few changes we have to address to get this project approved.
* [x] Let us enable linter checks on our repo, [visit this site for linter enabling](stickler-ci.com).
* [x] [Html validator](https://validator.w3.org/) is returning 2 errors and 8 warnings, let us address them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
* [x] Elements aligned with [float](https://css-tricks.com/all-about-floats/) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/float_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
The project require you to use ```float``` attribute of CSS to position elements, not ```flexbox```. You said it clearly in your P/R comment but I could not spot the implementation.
## That is it, kindly make these changes and submit the project for review
#### Happy coding
#### Addo Forison

**Comment by jaspreet-singh-sahota** [comment]
Addo Forison,
Thank you for the feedback. I am working on it now.
float CSS is used on aside-bar-
Screenshot from 2020-01-21 23-27-25

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @jaspreet-singh-sahota @Krishnabot  , 👋 You have done a great job in this project 👏 

* [ ]  Let us enable linter checks on our repo, [visit this site for linter enabling](https://stickler-ci.com/).
> Still it seems stickler is not enabled in this project. If you already enabled from the stickler site, then to trigger the stickler in this PR, just push a small dummy commit to it.
----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Review by fatymahmed — APPROVED** [review]
## Hi @jaspreet-singh-sahota  @Krishnabot 
It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
_Don't forget to submit your project completion form_

**Pull request merged**
